import { GoogleGenAI } from '@google/genai';

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';

const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

async function callGeminiWithRetry(
    models: string[],
    prompt: string,
    label: string,
    maxRounds = 3
): Promise<string> {
    let lastError: Error | null = null;

    for (let round = 0; round < maxRounds; round++) {
        // Each round tries all models in order
        for (const model of models) {
            try {
                console.log(`[${label}] Trying ${model} (round ${round + 1}/${maxRounds})...`);
                const response = await ai.models.generateContent({ model, contents: prompt });
                let html = response.text || '';
                html = html.replace(/^```html?\s*\n?/i, '').replace(/\n?```\s*$/i, '').trim();
                html = html.replace('</head>', `<!-- Generated by Sales DX (${model}) - ${label} -->\n</head>`);
                console.log(`[${label}] ✅ Success with ${model} (round ${round + 1})`);
                return html;
            } catch (err) {
                lastError = err instanceof Error ? err : new Error(String(err));
                const msg = lastError.message || '';
                console.warn(`[${label}] ${model} failed:`, msg.slice(0, 200));

                if (msg.includes('429') || msg.includes('RESOURCE_EXHAUSTED') || msg.includes('quota')) {
                    // Rate limited — immediately try next model (no wait yet)
                    console.log(`[${label}] ${model} rate limited, trying next model...`);
                    continue;
                }
                // Non-rate-limit error — also try next model
            }
        }

        // All models failed this round. Wait before next round (exponential backoff)
        if (round < maxRounds - 1) {
            const waitSec = Math.min(30 * Math.pow(2, round), 120);
            console.log(`[${label}] All models failed round ${round + 1}. Waiting ${waitSec}s before round ${round + 2}...`);
            await sleep(waitSec * 1000);
        }
    }

    throw lastError || new Error(`${label}: All models failed after ${maxRounds} rounds`);
}

interface GenerateInput {
    companyName: string;
    industry: string;
    area: string;
    address: string;
    websiteUrl: string;
    phone: string;
    issues: string[];
    praises: string[];
    recommendations: string[];
    reviews: string;
    businessDetails: string;
    score: number;
}

export async function generateSampleLP(input: GenerateInput): Promise<string> {
    const prompt = `あなたは利益最大化に特化した凄腕UI/UXデザイナー兼WEBマーケターです。
以下の[入力データ]を分析し、CV率（問い合わせ・成約）を極限まで高める「リニューアル後のスマホ版WEBデザイン（HTML）」を生成してください。

# 入力データ
- 業種：${input.industry || '不明'}
- ターゲット層：${input.industry || '中小企業'}の顧客層（${input.area || '地域'}密着型）
- 既存サイトの致命的な課題：${input.issues.length > 0 ? input.issues.join('、') : '特になし'}
- この企業の最大の強み：${input.praises.length > 0 ? input.praises.join('、') : '業界経験と実績'}

# 企業情報
- 企業名：${input.companyName}
- 所在地：${input.address || input.area || '不明'}
- 電話番号：${input.phone || '不明'}
- 現在のサイト：${input.websiteUrl || 'なし'}

# HTML生成の絶対要件
以下の要素を完全に満たす、モバイルファーストのランディングページ（またはコーポレートサイト）の高品質なUIデザインをHTMLで生成すること。

1. 全体レイアウトとトーン：
- DribbbleやBehanceのトップトレンドを意識した、クリーンで洗練されたプロフェッショナルなフラットデザイン。
- 無駄な装飾を完全に排し、ユーザーの視線誘導と情報の視認性を最優先する。
- ターゲット層に合わせた色彩心理（例：建設業なら信頼の青や力強い黒・オレンジ、美容なら清潔感のある白・ゴールド等）を適用する。

2. ヒーローセクション（ファーストビュー）：
- この企業の強みが一瞬で伝わる太字のキャッチコピーを配置。
- 背景には業種を象徴する、CSSグラデーションやパターンで高品質なビジュアルを表現。

3. CTA（行動喚起ボタン）：
- 画面内で最も目立つコントラストカラーを使用した巨大なボタンを配置する。
- ボタン周辺に「無料」「最短即日」など、心理的ハードルを下げるマイクロコピーを配置。

4. 信頼構築エリア（トラストフォーマット）：
- 施工実績、お客様の声、または権威性（有資格者、メディア掲載歴）を示すセクションを直感的なアイコンやカードUIで配置する。

5. お問い合わせセクション：
- 電話番号（${input.phone || 'XXX-XXXX-XXXX'}）をクリッカブルに配置
- フォーム風のCTAエリアを設ける

# 出力要件（絶対厳守）
- CDN経由でTailwind CSSを読み込んだ、1ファイルで完結するレスポンシブHTML（モバイルファースト）を出力すること。
- 挨拶、解説、総括、Markdownのコードブロック（\`\`\`html など）は一切出力してはならない。<!DOCTYPE html>から始まり、</html>で終わる純粋なソースコードのみを返すこと。
- スマートフォン画面で閲覧した時に最も美しく見えるようデザインすること。

出力はHTMLコードのみ。`;

    return callGeminiWithRetry(
        ['gemini-2.5-flash', 'gemini-2.0-flash'],
        prompt,
        `Sample LP for ${input.companyName}`
    );
}

interface ReportInput {
    companyName: string;
    industry: string;
    area: string;
    phone: string;
    websiteUrl: string;
    score: number;
    categoryScores: { category: string; score: number; maxScore: number }[];
    praises: string[];
    issues: string[];
    recommendations: string[];
    checks: { label: string; pass: boolean }[];
    sampleUrl: string;  // Vercel URL of the renewal LP
    sampleHtml: string;  // Raw HTML of the renewal LP
}

export async function generateDiagnosticReport(input: ReportInput): Promise<string> {
    const checksPass = input.checks.filter(c => c.pass).map(c => `✅ ${c.label}`).join('\n');
    const checksFail = input.checks.filter(c => !c.pass).map(c => `❌ ${c.label}`).join('\n');
    const catScores = input.categoryScores.map(c => `${c.category}: ${c.score}/${c.maxScore}`).join('\n');

    const prompt = `あなたは日本の零細〜中小企業の経営者に刺さる、冷徹かつ合理的なWEBコンサルタントです。
以下の[企業データ]と[サイト診断結果]を元に、代表者に「今すぐ動かなければ」と感じさせる**WEB診断レポート（HTML）**を生成してください。

# ターゲット読者
- ${input.industry || '中小企業'}の代表者・経営者
- ITリテラシーは高くない
- 見積書・請求書・帳票に見慣れている
- スマホで閲覧する

# 企業データ
- 企業名：${input.companyName}
- 業種：${input.industry || '不明'}
- 所在地：${input.area || '不明'}
- 電話番号：${input.phone || '不明'}
- 現在のサイト：${input.websiteUrl || 'なし'}

# サイト診断結果（${input.score}/100点）

## カテゴリ別スコア
${catScores}

## 合格項目
${checksPass || 'なし'}

## 不合格項目
${checksFail || 'なし'}

## 良い点
${input.praises.length > 0 ? input.praises.map(p => `- ${p}`).join('\n') : '- 特になし'}

## 改善すべき課題
${input.issues.length > 0 ? input.issues.map(i => `- ${i}`).join('\n') : '- 特になし'}

## 推奨アクション
${input.recommendations.length > 0 ? input.recommendations.map(r => `- ${r}`).join('\n') : '- 特になし'}

# 推論と構成（出力に反映。説明文は出力しない）
1. 診断データから「この企業が毎月いくらの機会損失をしているか」を推論し、金額で突きつける
2. ${input.industry}業界の構造的課題と照合し、代表者の「金か人の痛点」を特定する
3. 良い点は「御社の強み」として先に称え、信頼を獲得してから課題を指摘する（煽りすぎない）
4. 各不合格項目を「どういう機会損失に繋がるか」の言葉に変換する
5. 最後にリニューアル後のイメージへ誘導する流れを作る

# ページ構成（この順序で必ず構成すること）

## セクション1: ヘッダー（帳票風）
- 「${input.companyName} 様 WEBサイト無料診断レポート」
- 診断日、総合スコアを大きく表示
- 紺色背景＋白文字、見積書のような堅実なデザイン

## セクション2: 総合スコアと評価
- 100点満点中${input.score}点の意味を経営者向けに説明
- カテゴリ別スコアを棒グラフ風（CSSのみ）で表示
- スコアに応じた率直なコメント

## セクション3: 御社の強み（良い点）
- 診断で判明した良い点を「経営資産」として言語化
- 代表者の取り組みを労い、信頼関係を構築

## セクション4: 見逃している課題（煽りセクション）
- 不合格項目を「機会損失」の文脈で鋭く指摘
- 各課題が「月にいくらの損失か」「年間でどれだけの見込み客を逃しているか」を推論
- 現状維持の致命的リスクを提示（ただし脅しすぎず、事実ベースで冷静に）

## セクション5: 改善提案サマリー
- 推奨アクションを優先度順に整理
- 各改善策の期待効果（数値ベース）

## セクション6〜7: サイトプレビュー（自動挿入のため出力不要）
- 【重要】セクション5の改善提案サマリーの直後に、以下のHTMLコメントを正確に1行だけ出力してください：
<!-- SITE_PREVIEW_PLACEHOLDER -->
- このプレースホルダーの前後にサイトプレビューやリニューアルイメージに関する独自のHTML・テキストを一切出力しないこと
- 現在のサイトのiframeやリニューアル後のイメージは、システム側で自動挿入するため、あなたが生成する必要はありません

## セクション8: CTA（クロージング）
- 代表者への直接メッセージ（冷静かつ説得力のあるトーン）
- 電話番号をクリッカブルに表示
- 「まずは無料相談」的なシンプルなCTA

# デザイン要件（絶対厳守）
- CDN経由でTailwind CSSを読み込んだ1ファイル完結HTML
- 帳票・見積書に見慣れた経営者が読みやすいデザイン：
  - 紺色（#1b2e4b）のヘッダー、金色（#c5972c）のアクセント
  - 白背景、細い枠線、テーブル風レイアウト
  - 角丸は最小限（4px）、グラデーション不要
  - フォントは Noto Sans JP
- モバイルファースト、レスポンシブ
- 挨拶、解説、Markdownコードブロックは一切出力しない
- <!DOCTYPE html>から始まり</html>で終わる純粋なHTMLのみ

出力はHTMLコードのみ。`;

    let html = await callGeminiWithRetry(
        ['gemini-2.5-flash', 'gemini-2.0-flash'],
        prompt,
        `Diagnostic Report for ${input.companyName}`
    );

    if (html.length < 500) {
        throw new Error('診断レポートの出力が短すぎます');
    }

    // ============================================
    // Programmatically inject site preview iframes
    // (Gemini cannot be trusted to copy HTML verbatim)
    // ============================================
    // Escape sampleHtml for srcdoc attribute (only double quotes need escaping)
    const escapedSampleHtml = input.sampleHtml.replace(/"/g, '&quot;');

    const sitePreviewHtml = `
<!-- 現在のサイトプレビュー & リニューアル後イメージ（システム自動挿入） -->
<div style="max-width:700px;margin:40px auto 20px;">
  <div style="background:#64748b;color:#fff;padding:16px 20px;border-radius:4px 4px 0 0;text-align:center;border:1px solid #475569;border-bottom:none;">
    <h3 style="font-size:15px;font-weight:700;margin:0 0 2px;">🖥 ${input.companyName}様の現在のWEBサイト</h3>
    <p style="font-size:12px;opacity:0.85;margin:0;">上記の診断結果は、こちらのサイトを分析した結果です</p>
  </div>
  <div style="border:2px solid #94a3b8;border-top:none;border-radius:0 0 4px 4px;overflow:hidden;background:#fff;position:relative;">
    <span style="position:absolute;top:10px;left:10px;background:rgba(71,85,105,0.92);color:#fff;padding:4px 14px;border-radius:2px;font-size:11px;font-weight:700;letter-spacing:1px;z-index:2;">📍 現在のサイト</span>
    <iframe src="${input.websiteUrl}" title="現在のWEBサイト" loading="lazy" style="width:100%;border:none;min-height:70vh;display:block;"></iframe>
  </div>
  <div style="text-align:center;padding:8px 0;"><a href="${input.websiteUrl}" target="_blank" style="font-size:11px;color:#64748b;">サイトが表示されない場合はこちらをクリック →</a></div>
</div>
<div style="max-width:700px;margin:20px auto;padding:24px 0;text-align:center;">
  <p style="font-size:16px;font-weight:700;color:#1b2e4b;margin:0;">▼ 上記の課題をすべて解決したリニューアル後のイメージがこちらです ▼</p>
</div>
<div style="max-width:700px;margin:0 auto 40px;">
  <div style="background:#1b6b3a;color:#fff;padding:16px 20px;border-radius:4px 4px 0 0;text-align:center;border:1px solid #145a2e;border-bottom:none;">
    <h3 style="font-size:15px;font-weight:700;margin:0 0 2px;">✨ ${input.companyName}様 リニューアルイメージ</h3>
    <p style="font-size:12px;opacity:0.85;margin:0;">※ AIが自動生成した参考デザインです。実際の制作ではお打ち合わせの上デザインを決定します。</p>
  </div>
  <div style="border:2px solid #22a050;border-top:none;border-radius:0 0 4px 4px;overflow:hidden;background:#fff;position:relative;">
    <span style="position:absolute;top:10px;left:10px;background:rgba(27,107,58,0.92);color:#fff;padding:4px 14px;border-radius:2px;font-size:11px;font-weight:700;letter-spacing:1px;z-index:2;">🆕 リニューアル後</span>
    <iframe srcdoc="${escapedSampleHtml}" title="リニューアルイメージ" sandbox="allow-scripts" style="width:100%;border:none;min-height:80vh;display:block;"></iframe>
  </div>
</div>`;

    // Try to replace placeholder first
    if (html.includes('<!-- SITE_PREVIEW_PLACEHOLDER -->')) {
        html = html.replace('<!-- SITE_PREVIEW_PLACEHOLDER -->', sitePreviewHtml);
    } else if (html.includes('</body>')) {
        // Fallback: insert before </body> if placeholder not found
        console.warn('[DiagnosticReport] Placeholder not found, inserting before </body>');
        html = html.replace('</body>', sitePreviewHtml + '\n</body>');
    } else {
        // Last resort: append at the end before </html>
        console.warn('[DiagnosticReport] No </body> tag found, inserting before </html>');
        html = html.replace('</html>', sitePreviewHtml + '\n</html>');
    }

    return html;
}

/**
 * Edit existing LP HTML based on user instruction via chat
 */
export async function editLP(currentHtml: string, instruction: string): Promise<string> {
    const prompt = `あなたはプロのウェブデザイナーです。以下の既存HTMLを、ユーザーの指示に従って修正してください。

## ユーザーの指示
${instruction}

## ルール
1. 指示された部分のみ変更し、それ以外は極力変えない
2. 完全に動作するHTML1ファイルを出力（CSSインライン/CDN）
3. レスポンシブデザインを維持
4. 日本語で全て記述
5. HTMLコードのみ出力（説明文は不要）。\`\`\`html タグも不要
6. 構造やレイアウトを壊さないように注意

## 現在のHTML
${currentHtml}

上記HTMLを修正して、完全なHTMLコードのみを出力してください。`;

    const models = ['gemini-2.5-flash', 'gemini-2.0-flash'];

    let lastError: Error | null = null;
    for (const model of models) {
        try {
            const response = await ai.models.generateContent({
                model,
                contents: prompt,
            });

            let html = response.text || '';
            html = html.replace(/^```html?\s*\n?/i, '').replace(/\n?```\s*$/i, '').trim();

            if (html.length < 100) {
                throw new Error('出力が短すぎます');
            }

            return html;
        } catch (err) {
            lastError = err instanceof Error ? err : new Error(String(err));
            console.warn(`editLP: Model ${model} failed:`, lastError.message);
            continue;
        }
    }

    throw lastError || new Error('All models failed');
}
